### ISSUE TITLE
[EDH-3649] - Joint-invoice file not found

### ISSUE THREAD

**Issue by EinarArro** [Elering/estfeed-datahub-docs#140] opened 2024-12-04 12:29 UTC
## Problem

Joint invoice file is not downloadable

## Steps to reproduce

* Search for joint-invoice
* Try to download joint-invoice XML file. Example from LIVE:

```json
{
  "invoiceId": "hidden",
  "marketParticipantContext": {
    "marketParticipantIdentification": "38XVK-08600000-Q",
    "marketParticipantRole": "OPEN_SUPPLIER",
    "commodityType": "ELECTRICITY"
  }
}
```

## Expected result

Actual joint-invoice XML file is downloaded

## Actual Result

Erro:

```json
{
  "id": "cd553c75-18bb-49d2-af6a-b783da29e829",
  "cause": {
    "message": "An error has occurred while processing the request",
    "code": "opp.error.technical.general",
    "traceId": "5f1dd544f2544da4b142fe3f181f9d7b",
    "args": []
  }
}
```

## Impact (If known)

OS-s are not able to download joint-invoices.

## Work-a-round

None

**Comment by kristjanZ** [comment] 2024-12-06 13:31
The root cause has been fixed in Release 0.23.37
Missing invoices will be resent. 
Metadata of faulty invoices will be removed to avoid confusion.

**Closed by kristjanZ** 2024-12-06 13:31 UTC
Labels: critical
